### ISSUE TITLE
New Weapon: Templar Sword

### ISSUE THREAD

**Issue by XaserAcheron** [XaserAcheron/eriguns#28]
New Weapon: **Templar Sword**
> ![Templar Sword](https://i.imgur.com/7wsa1PP.png) ![Templar Sword Pickup](https://i.imgur.com/0Hm9dk7.png)

**Slot:** 1 (starting equipment in all games)
**Standard attack:** You swing a sword at people and turn them into half-people.
**Powered attack:** Glowy-runed vampire blade that sucks the life out of enemies. Delicious n' nutritious!

**Comment by WAR10CKfreeworld** [comment]
![sprite03](https://user-images.githubusercontent.com/4118365/32986047-44bcffe4-cc96-11e7-96a3-c4ef18460660.png)
![sprite02](https://user-images.githubusercontent.com/4118365/32986050-50f90c6c-cc96-11e7-913a-01896a38b83d.png)
![sprite01](https://user-images.githubusercontent.com/4118365/32986051-54893e92-cc96-11e7-812a-7d60a721fc4e.png)

Went ahead and cut out the rest of the sprites from the sheet for you.

**Comment by XaserAcheron** [comment]
Heh, I take it you noticed the `FREAKIN_SWORDS` branch. :P

I frankly wasn't sure what to do with those 3 additional sprites. They seemed more like alternate takes on the final frame more than anything else, so I left 'em out of the animation. Thanks there though!
