### ISSUE TITLE
Eriguns1 gldefs

### ISSUE THREAD

**Issue by mmaulwurff** [XaserAcheron/eriguns#34]
Hi! Is it intentional that weapons don't have OpenGL lights?
Maybe add [gldefs.txt](https://github.com/XaserAcheron/eriguns/files/1660230/gldefs.txt) to mod, or as optional pk3?
This file is just weapons section from GZDoom lights.pk3, adjusted for Eriguns1. It contains lights for bullet puff, rocket, plasma and BFG ball, and player light when shooting.

Later I may try to create light definitions for Eriguns2 weapons.

(Not sure where I should write about this: create issue here, or create a pull request, or bump forum topic).

**Comment by XaserAcheron** [comment]
Hey, thanks for this! Posting here's fine, though if you're up for making a pull request, I'll happily accept it.

The only reason for not having a GLDEFS is I don't regularly play with dynamic lights on so I never think of adding one. I'm certainly not against the concept, and it's a good bonus for folks who like this sort of thing.
